### ISSUE TITLE
Question about Attribute Quantization

### ISSUE THREAD

**Issue by cfchi** [Sharath-girish/efficientgaussian#1]
Hi, thanks for sharing your great work. 
I have a question about the datatype of each attribution after quantization.
In Section 4.1, Attribute Quantization, you mentioned that the base band color SH coefficient, scaling coefficients, and position vector are not encoded. 
I would like to confirm if it is correct that these attributes are stored in FP32 as 3DGS.

**Comment by Sharath-girish** [comment]
Thanks for your interest. Yes, they are currently stored as FP32 itself and are not compressed.
