### ISSUE TITLE
Question about rendering Power Needs for evaluation

### ISSUE THREAD

**Issue by m-mousatat** [Sharath-girish/efficientgaussian#3]
Thank you for your great work.
I would like to ask do you use the tile resertizer to render the images from the Quantized latent attributes during evaluation? How much GPU RAM do we need to render images with this high frame rate?
and is it possible to make real time renderer control like in .ply renderer so we can control the camera position in real time using the Quantized latent attributes instead of the point cload?

**Comment by Sharath-girish** [comment]
Hello, thank you for your interest. We decode our quantized latents on CPU before rendering the images on GPU. RAM usage for this is provided in the paper and is a bit lower than 3D-GS. 
This is a fixed one-time cost as the images can be rendered from different viewpoints continuously after decoding once. We currently do not focus on directly rendering from the quantized latents but will keep you updated in the future.
